In [1]:
import pandas as pd

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_data = pd.ExcelFile("crowdfunding.xlsx")

#get the sheet names
crowdfunding_data.sheet_names

['crowdfunding_info', 'contact_info']

In [3]:
# Get the crowdfunding_info from the crowdfunding_info worksheet. 
crowdfunding_info_df = pd.read_excel(crowdfunding_data, sheet_name = 'crowdfunding_info')

crowdfunding_info_df.head()

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [4]:
# Get the contact_info from the contact_info worksheet.
# Increase the width of the column.
pd.set_option('max_colwidth', 400)

contact_info_df = pd.read_excel(crowdfunding_data, sheet_name = 'contact_info', header=2)

contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

In [5]:
contact_info_df.sample(5)

649                          {"contact_id": 2213, "name": "Rosa Paul", "email": "rosa.paul@bien.com"}
826          {"contact_id": 2134, "name": "Gordon Vigorelli", "email": "gordon.vigorelli@solano.com"}
354                     {"contact_id": 4345, "name": "Kurt Sauer", "email": "kurt.sauer@almanza.biz"}
74   {"contact_id": 3571, "name": "Miranda Lacombe", "email": "miranda.lacombe@longoria-vanegas.net"}
488         {"contact_id": 3903, "name": "Cornelio Guardado", "email": "cornelio.guardado@gmail.com"}

In [6]:
crowdfunding_info_df.sample(5)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
392,2141,Hernandez-Grimes,Profit-focused zero administration forecast,102900,67546,failed,1608,US,USD,1609999200,1620450000,False,False,technology/wearables
69,1486,Jones-Watson,Switchable disintermediate moderator,7900,1901,canceled,17,US,USD,1624770000,1642399200,False,False,theater/plays
424,1653,Schmidt-Gomez,User-centric impactful projection,5100,2064,failed,83,US,USD,1622610000,1630731600,False,False,music/indie rock
685,865,Lee-Cobb,Customizable homogeneous firmware,140000,94501,failed,926,CA,CAD,1618376400,1641535200,False,False,theater/plays
891,1024,"Williams, Price and Hurley",Synchronized demand-driven infrastructure,3000,7758,successful,165,CA,CAD,1607839200,1629003600,False,False,film & video/documentary

In [7]:
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           1001 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [8]:
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   company_name             1000 non-null   object
 2   blurb                    1000 non-null   object
 3   goal                     1000 non-null   int64
 4   pledged                  1000 non-null   int64
 5   outcome                  1000 non-null   object
 6   backers_count            1000 non-null   int64
 7   country                  1000 non-null   object
 8   currency                 1000 non-null   object
 9   launched_at              1000 non-null   int64
 10  deadline                 1000 non-null   int64
 11  staff_pick               1000 non-null   bool
 12  spotlight                1000 non-null   bool
 13  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(6), object(6)
memory usage: 95.8+ KB

In [9]:
# Get the unique values in the category & sub-category column. 
crowdfunding_info_df["category & sub-category"].unique()

array(['food/food trucks', 'music/rock', 'technology/web',
       'theater/plays', 'film & video/documentary',
       'music/electric music', 'film & video/drama', 'music/indie rock',
       'technology/wearables', 'publishing/nonfiction',
       'film & video/animation', 'games/video games',
       'film & video/shorts', 'publishing/fiction',
       'photography/photography books', 'publishing/radio & podcasts',
       'music/metal', 'music/jazz', 'publishing/translations',
       'film & video/television', 'games/mobile games',
       'music/world music', 'film & video/science fiction',
       'journalism/audio'], dtype=object)

In [10]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df[["category","subcategory"]] = crowdfunding_info_df["category & sub-category"].str.split('/', n=1, expand=True)
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays,theater,plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary,film & video,documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays,theater,plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays,theater,plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music,music,electric music

In [11]:
# Get the distinct values in the category and subcategory columns.
print(crowdfunding_info_df["category"].nunique())
print(crowdfunding_info_df["subcategory"].nunique())

9
24

In [12]:
# Get the unique categories and subcategories in separate lists.
categories = crowdfunding_info_df["category"].unique()
subcategories = crowdfunding_info_df["subcategory"].unique()
print(categories)
print()
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']

['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [13]:
# Import the Numpy dependency
import numpy as np
# Create numpy arrays that have 1-10 for the category_ids and 1-25 for the subcategory_ids.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

In [14]:
category_ids

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Use a list comprehension to add "cat0" to each category_id. 
cat_ids = ["cat0" + str(cat_id) for cat_id in category_ids]

# Use a list comprehension to add "scat0" to each subcategory_id. 
scat_ids = ["scat0" + str(scat_id) for scat_id in subcategory_ids ]

print(cat_ids)
print(scat_ids)

['cat01', 'cat02', 'cat03', 'cat04', 'cat05', 'cat06', 'cat07', 'cat08', 'cat09']
['scat01', 'scat02', 'scat03', 'scat04', 'scat05', 'scat06', 'scat07', 'scat08', 'scat09', 'scat010', 'scat011', 'scat012', 'scat013', 'scat014', 'scat015', 'scat016', 'scat017', 'scat018', 'scat019', 'scat020', 'scat021', 'scat022', 'scat023', 'scat024']

In [16]:
crowdfunding_info_df.columns

Index(['cf_id', 'company_name', 'blurb', 'goal', 'pledged', 'outcome',
       'backers_count', 'country', 'currency', 'launched_at', 'deadline',
       'staff_pick', 'spotlight', 'category & sub-category', 'category',
       'subcategory'],
      dtype='object')

In [17]:
# Create a category DataFrame with the cat_ids array as the 
#category_id and categories list as the category name.
category_df = pd.DataFrame({'category_id': cat_ids, "category": categories})

# Create a subcategory DataFrame with the scat_ids array as the 
#subcategory_id and subcategories list as the subcategory name.
subcategory_df = pd.DataFrame({'subcategory_id': scat_ids, 'subcategories': subcategories})

In [18]:
category_df.head(10)

  category_id      category
0       cat01          food
1       cat02         music
2       cat03    technology
3       cat04       theater
4       cat05  film & video
5       cat06    publishing
6       cat07         games
7       cat08   photography
8       cat09    journalism

In [19]:
subcategory_df.head(10)

  subcategory_id   subcategories
0         scat01     food trucks
1         scat02            rock
2         scat03             web
3         scat04           plays
4         scat05     documentary
5         scat06  electric music
6         scat07           drama
7         scat08      indie rock
8         scat09       wearables
9        scat010      nonfiction

In [20]:
category_df.to_csv("category.csv", index=False)

In [21]:
subcategory_df.to_csv("subcategory.csv", index=False)

In [22]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df.
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [23]:
campaign_df = campaign_df.rename(columns={'blurb': 'description', 'launched_at': 'launched_date', 'deadline': 'end_date'})

In [24]:
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [25]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df[["goal","pledged"]] = campaign_df[["goal","pledged"]].astype(float)
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [26]:
# Format the launched_date and end_date columns to datetime format.
from datetime import datetime as dt
campaign_df["launched_date"] = pd.to_datetime(campaign_df["launched_date"], unit='s').dt.strftime('%Y-%m-%d') 
campaign_df["end_date"] = pd.to_datetime(campaign_df["end_date"], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays

In [27]:
# campaign_merged_df = category_df.merge(campaign_df, on='category', how='left')
# campaign_merged_df.head()

In [28]:
# campaign_df.info()

In [29]:
# subcategory_df.info()

In [30]:
# campaign_df.columns

In [31]:
# campaign_merged_df = subcategory_df.merge(subcategory_df, campaign_df, left_on='subcategories', right_on='subcategory', how='left')
# campaign_merged_df.head()

In [32]:
# subcategory_df.get('subcategory')

In [33]:
# # Merge the campaign_df with the category_df on the "category" column and 
# # the subcategory_df on the "subcategory" column.
# campaign_merged_df = campaign_df.merge(category_df, on='category', how='left').merge(subcategory_df, on='subcategory', how='left')
# campaign_merged_df.tail(10)

In [34]:
# # Merge the campaign_df with the category_df on the "category" column and 
# # the subcategory_df on the "subcategory" column.
# campaign_merged_df = campaign_df.merge(category_df, on='category', how='left').merge(campaign_df, subcategory_df,  left_on='subcategory', right_on='subcategories')
# campaign_merged_df.tail(10)

In [35]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = campaign_df.merge(category_df, on='category', how='left').merge(subcategory_df, on='subcategory', how='left')
campaign_merged_df.tail(10)

KeyError: 'subcategory'